// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

/**
 * <pre>
 * Basic Message Test Bean.
 * </pre>
 *
 * Protobuf type {@code crenjoy.protobuf.Basic2TestMessage}
 */
public final class Basic2TestMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.Basic2TestMessage)
    Basic2TestMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Basic2TestMessage.newBuilder() to construct.
  private Basic2TestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Basic2TestMessage() {
    testString_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Basic2TestMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_Basic2TestMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            crenjoy.protobuf.Basic2TestMessage.class, crenjoy.protobuf.Basic2TestMessage.Builder.class);
  }

  public static final int TEST_STRING_FIELD_NUMBER = 1;
  private volatile java.lang.Object testString_;
  /**
   * <code>string test_string = 1;</code>
   * @return The testString.
   */
  @java.lang.Override
  public java.lang.String getTestString() {
    java.lang.Object ref = testString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testString_ = s;
      return s;
    }
  }
  /**
   * <code>string test_string = 1;</code>
   * @return The bytes for testString.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestStringBytes() {
    java.lang.Object ref = testString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_INT32_FIELD_NUMBER = 2;
  private int testInt32_;
  /**
   * <code>int32 test_int32 = 2;</code>
   * @return The testInt32.
   */
  @java.lang.Override
  public int getTestInt32() {
    return testInt32_;
  }

  public static final int TEST_BOOL_FIELD_NUMBER = 3;
  private boolean testBool_;
  /**
   * <code>bool test_bool = 3;</code>
   * @return The testBool.
   */
  @java.lang.Override
  public boolean getTestBool() {
    return testBool_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testString_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testString_);
    }
    if (testInt32_ != 0) {
      output.writeInt32(2, testInt32_);
    }
    if (testBool_ != false) {
      output.writeBool(3, testBool_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testString_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testString_);
    }
    if (testInt32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, testInt32_);
    }
    if (testBool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, testBool_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof crenjoy.protobuf.Basic2TestMessage)) {
      return super.equals(obj);
    }
    crenjoy.protobuf.Basic2TestMessage other = (crenjoy.protobuf.Basic2TestMessage) obj;

    if (!getTestString()
        .equals(other.getTestString())) return false;
    if (getTestInt32()
        != other.getTestInt32()) return false;
    if (getTestBool()
        != other.getTestBool()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEST_STRING_FIELD_NUMBER;
    hash = (53 * hash) + getTestString().hashCode();
    hash = (37 * hash) + TEST_INT32_FIELD_NUMBER;
    hash = (53 * hash) + getTestInt32();
    hash = (37 * hash) + TEST_BOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTestBool());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.Basic2TestMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(crenjoy.protobuf.Basic2TestMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Basic Message Test Bean.
   * </pre>
   *
   * Protobuf type {@code crenjoy.protobuf.Basic2TestMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.Basic2TestMessage)
      crenjoy.protobuf.Basic2TestMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_Basic2TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crenjoy.protobuf.Basic2TestMessage.class, crenjoy.protobuf.Basic2TestMessage.Builder.class);
    }

    // Construct using crenjoy.protobuf.Basic2TestMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testString_ = "";

      testInt32_ = 0;

      testBool_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor;
    }

    @java.lang.Override
    public crenjoy.protobuf.Basic2TestMessage getDefaultInstanceForType() {
      return crenjoy.protobuf.Basic2TestMessage.getDefaultInstance();
    }

    @java.lang.Override
    public crenjoy.protobuf.Basic2TestMessage build() {
      crenjoy.protobuf.Basic2TestMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public crenjoy.protobuf.Basic2TestMessage buildPartial() {
      crenjoy.protobuf.Basic2TestMessage result = new crenjoy.protobuf.Basic2TestMessage(this);
      result.testString_ = testString_;
      result.testInt32_ = testInt32_;
      result.testBool_ = testBool_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof crenjoy.protobuf.Basic2TestMessage) {
        return mergeFrom((crenjoy.protobuf.Basic2TestMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(crenjoy.protobuf.Basic2TestMessage other) {
      if (other == crenjoy.protobuf.Basic2TestMessage.getDefaultInstance()) return this;
      if (!other.getTestString().isEmpty()) {
        testString_ = other.testString_;
        onChanged();
      }
      if (other.getTestInt32() != 0) {
        setTestInt32(other.getTestInt32());
      }
      if (other.getTestBool() != false) {
        setTestBool(other.getTestBool());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              testString_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              testInt32_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              testBool_ = input.readBool();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object testString_ = "";
    /**
     * <code>string test_string = 1;</code>
     * @return The testString.
     */
    public java.lang.String getTestString() {
      java.lang.Object ref = testString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_string = 1;</code>
     * @return The bytes for testString.
     */
    public com.google.protobuf.ByteString
        getTestStringBytes() {
      java.lang.Object ref = testString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_string = 1;</code>
     * @param value The testString to set.
     * @return This builder for chaining.
     */
    public Builder setTestString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_string = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestString() {
      
      testString_ = getDefaultInstance().getTestString();
      onChanged();
      return this;
    }
    /**
     * <code>string test_string = 1;</code>
     * @param value The bytes for testString to set.
     * @return This builder for chaining.
     */
    public Builder setTestStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testString_ = value;
      onChanged();
      return this;
    }

    private int testInt32_ ;
    /**
     * <code>int32 test_int32 = 2;</code>
     * @return The testInt32.
     */
    @java.lang.Override
    public int getTestInt32() {
      return testInt32_;
    }
    /**
     * <code>int32 test_int32 = 2;</code>
     * @param value The testInt32 to set.
     * @return This builder for chaining.
     */
    public Builder setTestInt32(int value) {
      
      testInt32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 test_int32 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestInt32() {
      
      testInt32_ = 0;
      onChanged();
      return this;
    }

    private boolean testBool_ ;
    /**
     * <code>bool test_bool = 3;</code>
     * @return The testBool.
     */
    @java.lang.Override
    public boolean getTestBool() {
      return testBool_;
    }
    /**
     * <code>bool test_bool = 3;</code>
     * @param value The testBool to set.
     * @return This builder for chaining.
     */
    public Builder setTestBool(boolean value) {
      
      testBool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool test_bool = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestBool() {
      
      testBool_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.Basic2TestMessage)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.Basic2TestMessage)
  private static final crenjoy.protobuf.Basic2TestMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new crenjoy.protobuf.Basic2TestMessage();
  }

  public static crenjoy.protobuf.Basic2TestMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Basic2TestMessage>
      PARSER = new com.google.protobuf.AbstractParser<Basic2TestMessage>() {
    @java.lang.Override
    public Basic2TestMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Basic2TestMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Basic2TestMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public crenjoy.protobuf.Basic2TestMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

