// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface BasicTestMessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.BasicTestMessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string test_str_list = 1;</code>
   * @return A list containing the testStrList.
   */
  java.util.List<java.lang.String>
      getTestStrListList();
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @return The count of testStrList.
   */
  int getTestStrListCount();
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @param index The index of the element to return.
   * @return The testStrList at the given index.
   */
  java.lang.String getTestStrList(int index);
  /**
   * <code>repeated string test_str_list = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the testStrList at the given index.
   */
  com.google.protobuf.ByteString
      getTestStrListBytes(int index);
}
