// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface Basic2TestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.Basic2TestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_string = 1;</code>
   * @return The testString.
   */
  java.lang.String getTestString();
  /**
   * <code>string test_string = 1;</code>
   * @return The bytes for testString.
   */
  com.google.protobuf.ByteString
      getTestStringBytes();

  /**
   * <code>int32 test_int32 = 2;</code>
   * @return The testInt32.
   */
  int getTestInt32();

  /**
   * <code>bool test_bool = 3;</code>
   * @return The testBool.
   */
  boolean getTestBool();
}
