// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public final class BasicTestMessageProto {
  private BasicTestMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_Basic1TestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_Basic1TestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_Basic2TestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_BasicTestMessageMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_BasicTestMessageList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_TestMessageMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_TestMessageMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_TestMessageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_TestMessageList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_NestedTestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_NestedTestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_NestedTestMessage_TestStrMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_NestedTestMessage_TestStrMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_NestedTestMessage_TestBasicMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_NestedTestMessage_TestBasicMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crenjoy_protobuf_ConvertTestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!crenjoy/protobuf/basic_test.proto\022\020cre" +
      "njoy.protobuf\"\316\002\n\021Basic1TestMessage\022\023\n\013t" +
      "est_double\030\001 \001(\001\022\022\n\ntest_float\030\002 \001(\002\022\022\n\n" +
      "test_int32\030\003 \001(\005\022\022\n\ntest_int64\030\004 \001(\003\022\023\n\013" +
      "test_uint32\030\005 \001(\r\022\023\n\013test_uint64\030\006 \001(\004\022\023" +
      "\n\013test_sint32\030\007 \001(\021\022\023\n\013test_sint64\030\010 \001(\022" +
      "\022\024\n\014test_fixed32\030\t \001(\007\022\024\n\014test_fixed64\030\n" +
      " \001(\006\022\025\n\rtest_sfixed32\030\013 \001(\017\022\025\n\rtest_sfix" +
      "ed64\030\014 \001(\020\022\021\n\ttest_bool\030\r \001(\010\022\023\n\013test_st" +
      "ring\030\016 \001(\t\022\022\n\ntest_bytes\030\017 \001(\014\"O\n\021Basic2" +
      "TestMessage\022\023\n\013test_string\030\001 \001(\t\022\022\n\ntest" +
      "_int32\030\002 \001(\005\022\021\n\ttest_bool\030\003 \001(\010\"\225\001\n\023Basi" +
      "cTestMessageMap\022K\n\014test_str_map\030\001 \003(\01325." +
      "crenjoy.protobuf.BasicTestMessageMap.Tes" +
      "tStrMapEntry\0321\n\017TestStrMapEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"-\n\024BasicTestMess" +
      "ageList\022\025\n\rtest_str_list\030\001 \003(\t\"\266\001\n\016TestM" +
      "essageMap\022J\n\016test_basic_map\030\001 \003(\01322.cren" +
      "joy.protobuf.TestMessageMap.TestBasicMap" +
      "Entry\032X\n\021TestBasicMapEntry\022\013\n\003key\030\001 \001(\t\022" +
      "2\n\005value\030\002 \001(\0132#.crenjoy.protobuf.Basic2" +
      "TestMessage:\0028\001\"O\n\017TestMessageList\022<\n\017te" +
      "st_basic_list\030\001 \003(\0132#.crenjoy.protobuf.B" +
      "asic2TestMessage\"\213\004\n\021NestedTestMessage\022\023" +
      "\n\013test_string\030\001 \001(\t\022\023\n\013test_double\030\002 \001(\001" +
      "\022\022\n\ntest_float\030\003 \001(\002\022<\n\017test_basic_bean\030" +
      "\004 \001(\0132#.crenjoy.protobuf.Basic2TestMessa" +
      "ge\022I\n\014test_str_map\030\005 \003(\01323.crenjoy.proto" +
      "buf.NestedTestMessage.TestStrMapEntry\022\025\n" +
      "\rtest_str_list\030\006 \003(\t\022M\n\016test_basic_map\030\007" +
      " \003(\01325.crenjoy.protobuf.NestedTestMessag" +
      "e.TestBasicMapEntry\022<\n\017test_basic_list\030\010" +
      " \003(\0132#.crenjoy.protobuf.Basic2TestMessag" +
      "e\0321\n\017TestStrMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\032X\n\021TestBasicMapEntry\022\013\n\003key" +
      "\030\001 \001(\t\0222\n\005value\030\002 \001(\0132#.crenjoy.protobuf" +
      ".Basic2TestMessage:\0028\001\"\312\002\n\022ConvertTestMe" +
      "ssage\022\034\n\024test_local_date_time\030\001 \001(\t\022\027\n\017t" +
      "est_local_date\030\002 \001(\t\022\027\n\017test_local_time\030" +
      "\003 \001(\t\022\024\n\014test_instant\030\004 \001(\t\022\025\n\rtest_dura" +
      "tion\030\005 \001(\t\022\035\n\025test_offset_date_time\030\006 \001(" +
      "\t\022\030\n\020test_offset_time\030\007 \001(\t\022\034\n\024test_zone" +
      "d_date_time\030\010 \001(\t\022\025\n\rtest_str_enum\030\t \001(\t" +
      "\022\025\n\rtest_int_enum\030\n \001(\005\022\030\n\020test_big_deci" +
      "mal\030\013 \001(\t\022\030\n\020test_big_integer\030\014 \001(\tB+\n\020c" +
      "renjoy.protobufB\025BasicTestMessageProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_crenjoy_protobuf_Basic1TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crenjoy_protobuf_Basic1TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_Basic1TestMessage_descriptor,
        new java.lang.String[] { "TestDouble", "TestFloat", "TestInt32", "TestInt64", "TestUint32", "TestUint64", "TestSint32", "TestSint64", "TestFixed32", "TestFixed64", "TestSfixed32", "TestSfixed64", "TestBool", "TestString", "TestBytes", });
    internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crenjoy_protobuf_Basic2TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_Basic2TestMessage_descriptor,
        new java.lang.String[] { "TestString", "TestInt32", "TestBool", });
    internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_crenjoy_protobuf_BasicTestMessageMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor,
        new java.lang.String[] { "TestStrMap", });
    internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_descriptor =
      internal_static_crenjoy_protobuf_BasicTestMessageMap_descriptor.getNestedTypes().get(0);
    internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_BasicTestMessageMap_TestStrMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_crenjoy_protobuf_BasicTestMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_BasicTestMessageList_descriptor,
        new java.lang.String[] { "TestStrList", });
    internal_static_crenjoy_protobuf_TestMessageMap_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_crenjoy_protobuf_TestMessageMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_TestMessageMap_descriptor,
        new java.lang.String[] { "TestBasicMap", });
    internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_descriptor =
      internal_static_crenjoy_protobuf_TestMessageMap_descriptor.getNestedTypes().get(0);
    internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crenjoy_protobuf_TestMessageList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_crenjoy_protobuf_TestMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_TestMessageList_descriptor,
        new java.lang.String[] { "TestBasicList", });
    internal_static_crenjoy_protobuf_NestedTestMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_crenjoy_protobuf_NestedTestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_NestedTestMessage_descriptor,
        new java.lang.String[] { "TestString", "TestDouble", "TestFloat", "TestBasicBean", "TestStrMap", "TestStrList", "TestBasicMap", "TestBasicList", });
    internal_static_crenjoy_protobuf_NestedTestMessage_TestStrMapEntry_descriptor =
      internal_static_crenjoy_protobuf_NestedTestMessage_descriptor.getNestedTypes().get(0);
    internal_static_crenjoy_protobuf_NestedTestMessage_TestStrMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_NestedTestMessage_TestStrMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crenjoy_protobuf_NestedTestMessage_TestBasicMapEntry_descriptor =
      internal_static_crenjoy_protobuf_NestedTestMessage_descriptor.getNestedTypes().get(1);
    internal_static_crenjoy_protobuf_NestedTestMessage_TestBasicMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_NestedTestMessage_TestBasicMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_crenjoy_protobuf_ConvertTestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor,
        new java.lang.String[] { "TestLocalDateTime", "TestLocalDate", "TestLocalTime", "TestInstant", "TestDuration", "TestOffsetDateTime", "TestOffsetTime", "TestZonedDateTime", "TestStrEnum", "TestIntEnum", "TestBigDecimal", "TestBigInteger", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
