// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface Basic1TestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.Basic1TestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double test_double = 1;</code>
   * @return The testDouble.
   */
  double getTestDouble();

  /**
   * <code>float test_float = 2;</code>
   * @return The testFloat.
   */
  float getTestFloat();

  /**
   * <code>int32 test_int32 = 3;</code>
   * @return The testInt32.
   */
  int getTestInt32();

  /**
   * <code>int64 test_int64 = 4;</code>
   * @return The testInt64.
   */
  long getTestInt64();

  /**
   * <code>uint32 test_uint32 = 5;</code>
   * @return The testUint32.
   */
  int getTestUint32();

  /**
   * <code>uint64 test_uint64 = 6;</code>
   * @return The testUint64.
   */
  long getTestUint64();

  /**
   * <code>sint32 test_sint32 = 7;</code>
   * @return The testSint32.
   */
  int getTestSint32();

  /**
   * <code>sint64 test_sint64 = 8;</code>
   * @return The testSint64.
   */
  long getTestSint64();

  /**
   * <code>fixed32 test_fixed32 = 9;</code>
   * @return The testFixed32.
   */
  int getTestFixed32();

  /**
   * <code>fixed64 test_fixed64 = 10;</code>
   * @return The testFixed64.
   */
  long getTestFixed64();

  /**
   * <code>sfixed32 test_sfixed32 = 11;</code>
   * @return The testSfixed32.
   */
  int getTestSfixed32();

  /**
   * <code>sfixed64 test_sfixed64 = 12;</code>
   * @return The testSfixed64.
   */
  long getTestSfixed64();

  /**
   * <code>bool test_bool = 13;</code>
   * @return The testBool.
   */
  boolean getTestBool();

  /**
   * <code>string test_string = 14;</code>
   * @return The testString.
   */
  java.lang.String getTestString();
  /**
   * <code>string test_string = 14;</code>
   * @return The bytes for testString.
   */
  com.google.protobuf.ByteString
      getTestStringBytes();

  /**
   * <code>bytes test_bytes = 15;</code>
   * @return The testBytes.
   */
  com.google.protobuf.ByteString getTestBytes();
}
