// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface BasicTestMessageMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.BasicTestMessageMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  int getTestStrMapCount();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  boolean containsTestStrMap(
      java.lang.String key);
  /**
   * Use {@link #getTestStrMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTestStrMap();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTestStrMapMap();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */

  /* nullable */
java.lang.String getTestStrMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; test_str_map = 1;</code>
   */

  java.lang.String getTestStrMapOrThrow(
      java.lang.String key);
}
