// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface ConvertTestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.ConvertTestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_local_date_time = 1;</code>
   * @return The testLocalDateTime.
   */
  java.lang.String getTestLocalDateTime();
  /**
   * <code>string test_local_date_time = 1;</code>
   * @return The bytes for testLocalDateTime.
   */
  com.google.protobuf.ByteString
      getTestLocalDateTimeBytes();

  /**
   * <code>string test_local_date = 2;</code>
   * @return The testLocalDate.
   */
  java.lang.String getTestLocalDate();
  /**
   * <code>string test_local_date = 2;</code>
   * @return The bytes for testLocalDate.
   */
  com.google.protobuf.ByteString
      getTestLocalDateBytes();

  /**
   * <code>string test_local_time = 3;</code>
   * @return The testLocalTime.
   */
  java.lang.String getTestLocalTime();
  /**
   * <code>string test_local_time = 3;</code>
   * @return The bytes for testLocalTime.
   */
  com.google.protobuf.ByteString
      getTestLocalTimeBytes();

  /**
   * <code>string test_instant = 4;</code>
   * @return The testInstant.
   */
  java.lang.String getTestInstant();
  /**
   * <code>string test_instant = 4;</code>
   * @return The bytes for testInstant.
   */
  com.google.protobuf.ByteString
      getTestInstantBytes();

  /**
   * <code>string test_duration = 5;</code>
   * @return The testDuration.
   */
  java.lang.String getTestDuration();
  /**
   * <code>string test_duration = 5;</code>
   * @return The bytes for testDuration.
   */
  com.google.protobuf.ByteString
      getTestDurationBytes();

  /**
   * <code>string test_offset_date_time = 6;</code>
   * @return The testOffsetDateTime.
   */
  java.lang.String getTestOffsetDateTime();
  /**
   * <code>string test_offset_date_time = 6;</code>
   * @return The bytes for testOffsetDateTime.
   */
  com.google.protobuf.ByteString
      getTestOffsetDateTimeBytes();

  /**
   * <code>string test_offset_time = 7;</code>
   * @return The testOffsetTime.
   */
  java.lang.String getTestOffsetTime();
  /**
   * <code>string test_offset_time = 7;</code>
   * @return The bytes for testOffsetTime.
   */
  com.google.protobuf.ByteString
      getTestOffsetTimeBytes();

  /**
   * <code>string test_zoned_date_time = 8;</code>
   * @return The testZonedDateTime.
   */
  java.lang.String getTestZonedDateTime();
  /**
   * <code>string test_zoned_date_time = 8;</code>
   * @return The bytes for testZonedDateTime.
   */
  com.google.protobuf.ByteString
      getTestZonedDateTimeBytes();

  /**
   * <code>string test_str_enum = 9;</code>
   * @return The testStrEnum.
   */
  java.lang.String getTestStrEnum();
  /**
   * <code>string test_str_enum = 9;</code>
   * @return The bytes for testStrEnum.
   */
  com.google.protobuf.ByteString
      getTestStrEnumBytes();

  /**
   * <code>int32 test_int_enum = 10;</code>
   * @return The testIntEnum.
   */
  int getTestIntEnum();

  /**
   * <code>string test_big_decimal = 11;</code>
   * @return The testBigDecimal.
   */
  java.lang.String getTestBigDecimal();
  /**
   * <code>string test_big_decimal = 11;</code>
   * @return The bytes for testBigDecimal.
   */
  com.google.protobuf.ByteString
      getTestBigDecimalBytes();

  /**
   * <code>string test_big_integer = 12;</code>
   * @return The testBigInteger.
   */
  java.lang.String getTestBigInteger();
  /**
   * <code>string test_big_integer = 12;</code>
   * @return The bytes for testBigInteger.
   */
  com.google.protobuf.ByteString
      getTestBigIntegerBytes();
}
