// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

/**
 * <pre>
 *Proto Message Convert POJO Bean.
 * </pre>
 *
 * Protobuf type {@code crenjoy.protobuf.ConvertTestMessage}
 */
public final class ConvertTestMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.ConvertTestMessage)
    ConvertTestMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConvertTestMessage.newBuilder() to construct.
  private ConvertTestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConvertTestMessage() {
    testLocalDateTime_ = "";
    testLocalDate_ = "";
    testLocalTime_ = "";
    testInstant_ = "";
    testDuration_ = "";
    testOffsetDateTime_ = "";
    testOffsetTime_ = "";
    testZonedDateTime_ = "";
    testStrEnum_ = "";
    testBigDecimal_ = "";
    testBigInteger_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConvertTestMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_ConvertTestMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            crenjoy.protobuf.ConvertTestMessage.class, crenjoy.protobuf.ConvertTestMessage.Builder.class);
  }

  public static final int TEST_LOCAL_DATE_TIME_FIELD_NUMBER = 1;
  private volatile java.lang.Object testLocalDateTime_;
  /**
   * <code>string test_local_date_time = 1;</code>
   * @return The testLocalDateTime.
   */
  @java.lang.Override
  public java.lang.String getTestLocalDateTime() {
    java.lang.Object ref = testLocalDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testLocalDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string test_local_date_time = 1;</code>
   * @return The bytes for testLocalDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestLocalDateTimeBytes() {
    java.lang.Object ref = testLocalDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testLocalDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_LOCAL_DATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object testLocalDate_;
  /**
   * <code>string test_local_date = 2;</code>
   * @return The testLocalDate.
   */
  @java.lang.Override
  public java.lang.String getTestLocalDate() {
    java.lang.Object ref = testLocalDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testLocalDate_ = s;
      return s;
    }
  }
  /**
   * <code>string test_local_date = 2;</code>
   * @return The bytes for testLocalDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestLocalDateBytes() {
    java.lang.Object ref = testLocalDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testLocalDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_LOCAL_TIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object testLocalTime_;
  /**
   * <code>string test_local_time = 3;</code>
   * @return The testLocalTime.
   */
  @java.lang.Override
  public java.lang.String getTestLocalTime() {
    java.lang.Object ref = testLocalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testLocalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string test_local_time = 3;</code>
   * @return The bytes for testLocalTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestLocalTimeBytes() {
    java.lang.Object ref = testLocalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testLocalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_INSTANT_FIELD_NUMBER = 4;
  private volatile java.lang.Object testInstant_;
  /**
   * <code>string test_instant = 4;</code>
   * @return The testInstant.
   */
  @java.lang.Override
  public java.lang.String getTestInstant() {
    java.lang.Object ref = testInstant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testInstant_ = s;
      return s;
    }
  }
  /**
   * <code>string test_instant = 4;</code>
   * @return The bytes for testInstant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestInstantBytes() {
    java.lang.Object ref = testInstant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testInstant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_DURATION_FIELD_NUMBER = 5;
  private volatile java.lang.Object testDuration_;
  /**
   * <code>string test_duration = 5;</code>
   * @return The testDuration.
   */
  @java.lang.Override
  public java.lang.String getTestDuration() {
    java.lang.Object ref = testDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string test_duration = 5;</code>
   * @return The bytes for testDuration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestDurationBytes() {
    java.lang.Object ref = testDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_OFFSET_DATE_TIME_FIELD_NUMBER = 6;
  private volatile java.lang.Object testOffsetDateTime_;
  /**
   * <code>string test_offset_date_time = 6;</code>
   * @return The testOffsetDateTime.
   */
  @java.lang.Override
  public java.lang.String getTestOffsetDateTime() {
    java.lang.Object ref = testOffsetDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testOffsetDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string test_offset_date_time = 6;</code>
   * @return The bytes for testOffsetDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestOffsetDateTimeBytes() {
    java.lang.Object ref = testOffsetDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testOffsetDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_OFFSET_TIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object testOffsetTime_;
  /**
   * <code>string test_offset_time = 7;</code>
   * @return The testOffsetTime.
   */
  @java.lang.Override
  public java.lang.String getTestOffsetTime() {
    java.lang.Object ref = testOffsetTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testOffsetTime_ = s;
      return s;
    }
  }
  /**
   * <code>string test_offset_time = 7;</code>
   * @return The bytes for testOffsetTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestOffsetTimeBytes() {
    java.lang.Object ref = testOffsetTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testOffsetTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_ZONED_DATE_TIME_FIELD_NUMBER = 8;
  private volatile java.lang.Object testZonedDateTime_;
  /**
   * <code>string test_zoned_date_time = 8;</code>
   * @return The testZonedDateTime.
   */
  @java.lang.Override
  public java.lang.String getTestZonedDateTime() {
    java.lang.Object ref = testZonedDateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testZonedDateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string test_zoned_date_time = 8;</code>
   * @return The bytes for testZonedDateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestZonedDateTimeBytes() {
    java.lang.Object ref = testZonedDateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testZonedDateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_STR_ENUM_FIELD_NUMBER = 9;
  private volatile java.lang.Object testStrEnum_;
  /**
   * <code>string test_str_enum = 9;</code>
   * @return The testStrEnum.
   */
  @java.lang.Override
  public java.lang.String getTestStrEnum() {
    java.lang.Object ref = testStrEnum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testStrEnum_ = s;
      return s;
    }
  }
  /**
   * <code>string test_str_enum = 9;</code>
   * @return The bytes for testStrEnum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestStrEnumBytes() {
    java.lang.Object ref = testStrEnum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testStrEnum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_INT_ENUM_FIELD_NUMBER = 10;
  private int testIntEnum_;
  /**
   * <code>int32 test_int_enum = 10;</code>
   * @return The testIntEnum.
   */
  @java.lang.Override
  public int getTestIntEnum() {
    return testIntEnum_;
  }

  public static final int TEST_BIG_DECIMAL_FIELD_NUMBER = 11;
  private volatile java.lang.Object testBigDecimal_;
  /**
   * <code>string test_big_decimal = 11;</code>
   * @return The testBigDecimal.
   */
  @java.lang.Override
  public java.lang.String getTestBigDecimal() {
    java.lang.Object ref = testBigDecimal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testBigDecimal_ = s;
      return s;
    }
  }
  /**
   * <code>string test_big_decimal = 11;</code>
   * @return The bytes for testBigDecimal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestBigDecimalBytes() {
    java.lang.Object ref = testBigDecimal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testBigDecimal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEST_BIG_INTEGER_FIELD_NUMBER = 12;
  private volatile java.lang.Object testBigInteger_;
  /**
   * <code>string test_big_integer = 12;</code>
   * @return The testBigInteger.
   */
  @java.lang.Override
  public java.lang.String getTestBigInteger() {
    java.lang.Object ref = testBigInteger_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      testBigInteger_ = s;
      return s;
    }
  }
  /**
   * <code>string test_big_integer = 12;</code>
   * @return The bytes for testBigInteger.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTestBigIntegerBytes() {
    java.lang.Object ref = testBigInteger_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      testBigInteger_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, testLocalDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, testLocalDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, testLocalTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testInstant_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, testInstant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testDuration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, testDuration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testOffsetDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, testOffsetDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testOffsetTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, testOffsetTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testZonedDateTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, testZonedDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testStrEnum_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, testStrEnum_);
    }
    if (testIntEnum_ != 0) {
      output.writeInt32(10, testIntEnum_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testBigDecimal_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, testBigDecimal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testBigInteger_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, testBigInteger_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, testLocalDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, testLocalDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testLocalTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, testLocalTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testInstant_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, testInstant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testDuration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, testDuration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testOffsetDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, testOffsetDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testOffsetTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, testOffsetTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testZonedDateTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, testZonedDateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testStrEnum_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, testStrEnum_);
    }
    if (testIntEnum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, testIntEnum_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testBigDecimal_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, testBigDecimal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(testBigInteger_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, testBigInteger_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof crenjoy.protobuf.ConvertTestMessage)) {
      return super.equals(obj);
    }
    crenjoy.protobuf.ConvertTestMessage other = (crenjoy.protobuf.ConvertTestMessage) obj;

    if (!getTestLocalDateTime()
        .equals(other.getTestLocalDateTime())) return false;
    if (!getTestLocalDate()
        .equals(other.getTestLocalDate())) return false;
    if (!getTestLocalTime()
        .equals(other.getTestLocalTime())) return false;
    if (!getTestInstant()
        .equals(other.getTestInstant())) return false;
    if (!getTestDuration()
        .equals(other.getTestDuration())) return false;
    if (!getTestOffsetDateTime()
        .equals(other.getTestOffsetDateTime())) return false;
    if (!getTestOffsetTime()
        .equals(other.getTestOffsetTime())) return false;
    if (!getTestZonedDateTime()
        .equals(other.getTestZonedDateTime())) return false;
    if (!getTestStrEnum()
        .equals(other.getTestStrEnum())) return false;
    if (getTestIntEnum()
        != other.getTestIntEnum()) return false;
    if (!getTestBigDecimal()
        .equals(other.getTestBigDecimal())) return false;
    if (!getTestBigInteger()
        .equals(other.getTestBigInteger())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEST_LOCAL_DATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTestLocalDateTime().hashCode();
    hash = (37 * hash) + TEST_LOCAL_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getTestLocalDate().hashCode();
    hash = (37 * hash) + TEST_LOCAL_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTestLocalTime().hashCode();
    hash = (37 * hash) + TEST_INSTANT_FIELD_NUMBER;
    hash = (53 * hash) + getTestInstant().hashCode();
    hash = (37 * hash) + TEST_DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getTestDuration().hashCode();
    hash = (37 * hash) + TEST_OFFSET_DATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTestOffsetDateTime().hashCode();
    hash = (37 * hash) + TEST_OFFSET_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTestOffsetTime().hashCode();
    hash = (37 * hash) + TEST_ZONED_DATE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTestZonedDateTime().hashCode();
    hash = (37 * hash) + TEST_STR_ENUM_FIELD_NUMBER;
    hash = (53 * hash) + getTestStrEnum().hashCode();
    hash = (37 * hash) + TEST_INT_ENUM_FIELD_NUMBER;
    hash = (53 * hash) + getTestIntEnum();
    hash = (37 * hash) + TEST_BIG_DECIMAL_FIELD_NUMBER;
    hash = (53 * hash) + getTestBigDecimal().hashCode();
    hash = (37 * hash) + TEST_BIG_INTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getTestBigInteger().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.ConvertTestMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(crenjoy.protobuf.ConvertTestMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Proto Message Convert POJO Bean.
   * </pre>
   *
   * Protobuf type {@code crenjoy.protobuf.ConvertTestMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.ConvertTestMessage)
      crenjoy.protobuf.ConvertTestMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_ConvertTestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crenjoy.protobuf.ConvertTestMessage.class, crenjoy.protobuf.ConvertTestMessage.Builder.class);
    }

    // Construct using crenjoy.protobuf.ConvertTestMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      testLocalDateTime_ = "";

      testLocalDate_ = "";

      testLocalTime_ = "";

      testInstant_ = "";

      testDuration_ = "";

      testOffsetDateTime_ = "";

      testOffsetTime_ = "";

      testZonedDateTime_ = "";

      testStrEnum_ = "";

      testIntEnum_ = 0;

      testBigDecimal_ = "";

      testBigInteger_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_ConvertTestMessage_descriptor;
    }

    @java.lang.Override
    public crenjoy.protobuf.ConvertTestMessage getDefaultInstanceForType() {
      return crenjoy.protobuf.ConvertTestMessage.getDefaultInstance();
    }

    @java.lang.Override
    public crenjoy.protobuf.ConvertTestMessage build() {
      crenjoy.protobuf.ConvertTestMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public crenjoy.protobuf.ConvertTestMessage buildPartial() {
      crenjoy.protobuf.ConvertTestMessage result = new crenjoy.protobuf.ConvertTestMessage(this);
      result.testLocalDateTime_ = testLocalDateTime_;
      result.testLocalDate_ = testLocalDate_;
      result.testLocalTime_ = testLocalTime_;
      result.testInstant_ = testInstant_;
      result.testDuration_ = testDuration_;
      result.testOffsetDateTime_ = testOffsetDateTime_;
      result.testOffsetTime_ = testOffsetTime_;
      result.testZonedDateTime_ = testZonedDateTime_;
      result.testStrEnum_ = testStrEnum_;
      result.testIntEnum_ = testIntEnum_;
      result.testBigDecimal_ = testBigDecimal_;
      result.testBigInteger_ = testBigInteger_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof crenjoy.protobuf.ConvertTestMessage) {
        return mergeFrom((crenjoy.protobuf.ConvertTestMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(crenjoy.protobuf.ConvertTestMessage other) {
      if (other == crenjoy.protobuf.ConvertTestMessage.getDefaultInstance()) return this;
      if (!other.getTestLocalDateTime().isEmpty()) {
        testLocalDateTime_ = other.testLocalDateTime_;
        onChanged();
      }
      if (!other.getTestLocalDate().isEmpty()) {
        testLocalDate_ = other.testLocalDate_;
        onChanged();
      }
      if (!other.getTestLocalTime().isEmpty()) {
        testLocalTime_ = other.testLocalTime_;
        onChanged();
      }
      if (!other.getTestInstant().isEmpty()) {
        testInstant_ = other.testInstant_;
        onChanged();
      }
      if (!other.getTestDuration().isEmpty()) {
        testDuration_ = other.testDuration_;
        onChanged();
      }
      if (!other.getTestOffsetDateTime().isEmpty()) {
        testOffsetDateTime_ = other.testOffsetDateTime_;
        onChanged();
      }
      if (!other.getTestOffsetTime().isEmpty()) {
        testOffsetTime_ = other.testOffsetTime_;
        onChanged();
      }
      if (!other.getTestZonedDateTime().isEmpty()) {
        testZonedDateTime_ = other.testZonedDateTime_;
        onChanged();
      }
      if (!other.getTestStrEnum().isEmpty()) {
        testStrEnum_ = other.testStrEnum_;
        onChanged();
      }
      if (other.getTestIntEnum() != 0) {
        setTestIntEnum(other.getTestIntEnum());
      }
      if (!other.getTestBigDecimal().isEmpty()) {
        testBigDecimal_ = other.testBigDecimal_;
        onChanged();
      }
      if (!other.getTestBigInteger().isEmpty()) {
        testBigInteger_ = other.testBigInteger_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              testLocalDateTime_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              testLocalDate_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              testLocalTime_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              testInstant_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              testDuration_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              testOffsetDateTime_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              testOffsetTime_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              testZonedDateTime_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 74: {
              testStrEnum_ = input.readStringRequireUtf8();

              break;
            } // case 74
            case 80: {
              testIntEnum_ = input.readInt32();

              break;
            } // case 80
            case 90: {
              testBigDecimal_ = input.readStringRequireUtf8();

              break;
            } // case 90
            case 98: {
              testBigInteger_ = input.readStringRequireUtf8();

              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object testLocalDateTime_ = "";
    /**
     * <code>string test_local_date_time = 1;</code>
     * @return The testLocalDateTime.
     */
    public java.lang.String getTestLocalDateTime() {
      java.lang.Object ref = testLocalDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testLocalDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_local_date_time = 1;</code>
     * @return The bytes for testLocalDateTime.
     */
    public com.google.protobuf.ByteString
        getTestLocalDateTimeBytes() {
      java.lang.Object ref = testLocalDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testLocalDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_local_date_time = 1;</code>
     * @param value The testLocalDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testLocalDateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_date_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestLocalDateTime() {
      
      testLocalDateTime_ = getDefaultInstance().getTestLocalDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_date_time = 1;</code>
     * @param value The bytes for testLocalDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testLocalDateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testLocalDate_ = "";
    /**
     * <code>string test_local_date = 2;</code>
     * @return The testLocalDate.
     */
    public java.lang.String getTestLocalDate() {
      java.lang.Object ref = testLocalDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testLocalDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_local_date = 2;</code>
     * @return The bytes for testLocalDate.
     */
    public com.google.protobuf.ByteString
        getTestLocalDateBytes() {
      java.lang.Object ref = testLocalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testLocalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_local_date = 2;</code>
     * @param value The testLocalDate to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testLocalDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_date = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestLocalDate() {
      
      testLocalDate_ = getDefaultInstance().getTestLocalDate();
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_date = 2;</code>
     * @param value The bytes for testLocalDate to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testLocalDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testLocalTime_ = "";
    /**
     * <code>string test_local_time = 3;</code>
     * @return The testLocalTime.
     */
    public java.lang.String getTestLocalTime() {
      java.lang.Object ref = testLocalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testLocalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_local_time = 3;</code>
     * @return The bytes for testLocalTime.
     */
    public com.google.protobuf.ByteString
        getTestLocalTimeBytes() {
      java.lang.Object ref = testLocalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testLocalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_local_time = 3;</code>
     * @param value The testLocalTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testLocalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_time = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestLocalTime() {
      
      testLocalTime_ = getDefaultInstance().getTestLocalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string test_local_time = 3;</code>
     * @param value The bytes for testLocalTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestLocalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testLocalTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testInstant_ = "";
    /**
     * <code>string test_instant = 4;</code>
     * @return The testInstant.
     */
    public java.lang.String getTestInstant() {
      java.lang.Object ref = testInstant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testInstant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_instant = 4;</code>
     * @return The bytes for testInstant.
     */
    public com.google.protobuf.ByteString
        getTestInstantBytes() {
      java.lang.Object ref = testInstant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testInstant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_instant = 4;</code>
     * @param value The testInstant to set.
     * @return This builder for chaining.
     */
    public Builder setTestInstant(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testInstant_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_instant = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestInstant() {
      
      testInstant_ = getDefaultInstance().getTestInstant();
      onChanged();
      return this;
    }
    /**
     * <code>string test_instant = 4;</code>
     * @param value The bytes for testInstant to set.
     * @return This builder for chaining.
     */
    public Builder setTestInstantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testInstant_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testDuration_ = "";
    /**
     * <code>string test_duration = 5;</code>
     * @return The testDuration.
     */
    public java.lang.String getTestDuration() {
      java.lang.Object ref = testDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_duration = 5;</code>
     * @return The bytes for testDuration.
     */
    public com.google.protobuf.ByteString
        getTestDurationBytes() {
      java.lang.Object ref = testDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_duration = 5;</code>
     * @param value The testDuration to set.
     * @return This builder for chaining.
     */
    public Builder setTestDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_duration = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestDuration() {
      
      testDuration_ = getDefaultInstance().getTestDuration();
      onChanged();
      return this;
    }
    /**
     * <code>string test_duration = 5;</code>
     * @param value The bytes for testDuration to set.
     * @return This builder for chaining.
     */
    public Builder setTestDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testDuration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testOffsetDateTime_ = "";
    /**
     * <code>string test_offset_date_time = 6;</code>
     * @return The testOffsetDateTime.
     */
    public java.lang.String getTestOffsetDateTime() {
      java.lang.Object ref = testOffsetDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testOffsetDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_offset_date_time = 6;</code>
     * @return The bytes for testOffsetDateTime.
     */
    public com.google.protobuf.ByteString
        getTestOffsetDateTimeBytes() {
      java.lang.Object ref = testOffsetDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testOffsetDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_offset_date_time = 6;</code>
     * @param value The testOffsetDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestOffsetDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testOffsetDateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_offset_date_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestOffsetDateTime() {
      
      testOffsetDateTime_ = getDefaultInstance().getTestOffsetDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string test_offset_date_time = 6;</code>
     * @param value The bytes for testOffsetDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestOffsetDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testOffsetDateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testOffsetTime_ = "";
    /**
     * <code>string test_offset_time = 7;</code>
     * @return The testOffsetTime.
     */
    public java.lang.String getTestOffsetTime() {
      java.lang.Object ref = testOffsetTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testOffsetTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_offset_time = 7;</code>
     * @return The bytes for testOffsetTime.
     */
    public com.google.protobuf.ByteString
        getTestOffsetTimeBytes() {
      java.lang.Object ref = testOffsetTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testOffsetTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_offset_time = 7;</code>
     * @param value The testOffsetTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestOffsetTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testOffsetTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_offset_time = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestOffsetTime() {
      
      testOffsetTime_ = getDefaultInstance().getTestOffsetTime();
      onChanged();
      return this;
    }
    /**
     * <code>string test_offset_time = 7;</code>
     * @param value The bytes for testOffsetTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestOffsetTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testOffsetTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testZonedDateTime_ = "";
    /**
     * <code>string test_zoned_date_time = 8;</code>
     * @return The testZonedDateTime.
     */
    public java.lang.String getTestZonedDateTime() {
      java.lang.Object ref = testZonedDateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testZonedDateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_zoned_date_time = 8;</code>
     * @return The bytes for testZonedDateTime.
     */
    public com.google.protobuf.ByteString
        getTestZonedDateTimeBytes() {
      java.lang.Object ref = testZonedDateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testZonedDateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_zoned_date_time = 8;</code>
     * @param value The testZonedDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestZonedDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testZonedDateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_zoned_date_time = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestZonedDateTime() {
      
      testZonedDateTime_ = getDefaultInstance().getTestZonedDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string test_zoned_date_time = 8;</code>
     * @param value The bytes for testZonedDateTime to set.
     * @return This builder for chaining.
     */
    public Builder setTestZonedDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testZonedDateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testStrEnum_ = "";
    /**
     * <code>string test_str_enum = 9;</code>
     * @return The testStrEnum.
     */
    public java.lang.String getTestStrEnum() {
      java.lang.Object ref = testStrEnum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testStrEnum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_str_enum = 9;</code>
     * @return The bytes for testStrEnum.
     */
    public com.google.protobuf.ByteString
        getTestStrEnumBytes() {
      java.lang.Object ref = testStrEnum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testStrEnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_str_enum = 9;</code>
     * @param value The testStrEnum to set.
     * @return This builder for chaining.
     */
    public Builder setTestStrEnum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testStrEnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_str_enum = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestStrEnum() {
      
      testStrEnum_ = getDefaultInstance().getTestStrEnum();
      onChanged();
      return this;
    }
    /**
     * <code>string test_str_enum = 9;</code>
     * @param value The bytes for testStrEnum to set.
     * @return This builder for chaining.
     */
    public Builder setTestStrEnumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testStrEnum_ = value;
      onChanged();
      return this;
    }

    private int testIntEnum_ ;
    /**
     * <code>int32 test_int_enum = 10;</code>
     * @return The testIntEnum.
     */
    @java.lang.Override
    public int getTestIntEnum() {
      return testIntEnum_;
    }
    /**
     * <code>int32 test_int_enum = 10;</code>
     * @param value The testIntEnum to set.
     * @return This builder for chaining.
     */
    public Builder setTestIntEnum(int value) {
      
      testIntEnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 test_int_enum = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestIntEnum() {
      
      testIntEnum_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object testBigDecimal_ = "";
    /**
     * <code>string test_big_decimal = 11;</code>
     * @return The testBigDecimal.
     */
    public java.lang.String getTestBigDecimal() {
      java.lang.Object ref = testBigDecimal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testBigDecimal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_big_decimal = 11;</code>
     * @return The bytes for testBigDecimal.
     */
    public com.google.protobuf.ByteString
        getTestBigDecimalBytes() {
      java.lang.Object ref = testBigDecimal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testBigDecimal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_big_decimal = 11;</code>
     * @param value The testBigDecimal to set.
     * @return This builder for chaining.
     */
    public Builder setTestBigDecimal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testBigDecimal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_big_decimal = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestBigDecimal() {
      
      testBigDecimal_ = getDefaultInstance().getTestBigDecimal();
      onChanged();
      return this;
    }
    /**
     * <code>string test_big_decimal = 11;</code>
     * @param value The bytes for testBigDecimal to set.
     * @return This builder for chaining.
     */
    public Builder setTestBigDecimalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testBigDecimal_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object testBigInteger_ = "";
    /**
     * <code>string test_big_integer = 12;</code>
     * @return The testBigInteger.
     */
    public java.lang.String getTestBigInteger() {
      java.lang.Object ref = testBigInteger_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        testBigInteger_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string test_big_integer = 12;</code>
     * @return The bytes for testBigInteger.
     */
    public com.google.protobuf.ByteString
        getTestBigIntegerBytes() {
      java.lang.Object ref = testBigInteger_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testBigInteger_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string test_big_integer = 12;</code>
     * @param value The testBigInteger to set.
     * @return This builder for chaining.
     */
    public Builder setTestBigInteger(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      testBigInteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string test_big_integer = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTestBigInteger() {
      
      testBigInteger_ = getDefaultInstance().getTestBigInteger();
      onChanged();
      return this;
    }
    /**
     * <code>string test_big_integer = 12;</code>
     * @param value The bytes for testBigInteger to set.
     * @return This builder for chaining.
     */
    public Builder setTestBigIntegerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      testBigInteger_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.ConvertTestMessage)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.ConvertTestMessage)
  private static final crenjoy.protobuf.ConvertTestMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new crenjoy.protobuf.ConvertTestMessage();
  }

  public static crenjoy.protobuf.ConvertTestMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConvertTestMessage>
      PARSER = new com.google.protobuf.AbstractParser<ConvertTestMessage>() {
    @java.lang.Override
    public ConvertTestMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConvertTestMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConvertTestMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public crenjoy.protobuf.ConvertTestMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

