// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface NestedTestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.NestedTestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string test_string = 1;</code>
   * @return The testString.
   */
  java.lang.String getTestString();
  /**
   * <code>string test_string = 1;</code>
   * @return The bytes for testString.
   */
  com.google.protobuf.ByteString
      getTestStringBytes();

  /**
   * <code>double test_double = 2;</code>
   * @return The testDouble.
   */
  double getTestDouble();

  /**
   * <code>float test_float = 3;</code>
   * @return The testFloat.
   */
  float getTestFloat();

  /**
   * <code>.crenjoy.protobuf.Basic2TestMessage test_basic_bean = 4;</code>
   * @return Whether the testBasicBean field is set.
   */
  boolean hasTestBasicBean();
  /**
   * <code>.crenjoy.protobuf.Basic2TestMessage test_basic_bean = 4;</code>
   * @return The testBasicBean.
   */
  crenjoy.protobuf.Basic2TestMessage getTestBasicBean();
  /**
   * <code>.crenjoy.protobuf.Basic2TestMessage test_basic_bean = 4;</code>
   */
  crenjoy.protobuf.Basic2TestMessageOrBuilder getTestBasicBeanOrBuilder();

  /**
   * <code>map&lt;string, string&gt; test_str_map = 5;</code>
   */
  int getTestStrMapCount();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 5;</code>
   */
  boolean containsTestStrMap(
      java.lang.String key);
  /**
   * Use {@link #getTestStrMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTestStrMap();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTestStrMapMap();
  /**
   * <code>map&lt;string, string&gt; test_str_map = 5;</code>
   */

  /* nullable */
java.lang.String getTestStrMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; test_str_map = 5;</code>
   */

  java.lang.String getTestStrMapOrThrow(
      java.lang.String key);

  /**
   * <code>repeated string test_str_list = 6;</code>
   * @return A list containing the testStrList.
   */
  java.util.List<java.lang.String>
      getTestStrListList();
  /**
   * <code>repeated string test_str_list = 6;</code>
   * @return The count of testStrList.
   */
  int getTestStrListCount();
  /**
   * <code>repeated string test_str_list = 6;</code>
   * @param index The index of the element to return.
   * @return The testStrList at the given index.
   */
  java.lang.String getTestStrList(int index);
  /**
   * <code>repeated string test_str_list = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the testStrList at the given index.
   */
  com.google.protobuf.ByteString
      getTestStrListBytes(int index);

  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 7;</code>
   */
  int getTestBasicMapCount();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 7;</code>
   */
  boolean containsTestBasicMap(
      java.lang.String key);
  /**
   * Use {@link #getTestBasicMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
  getTestBasicMap();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 7;</code>
   */
  java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
  getTestBasicMapMap();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 7;</code>
   */

  /* nullable */
crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrDefault(
      java.lang.String key,
      /* nullable */
crenjoy.protobuf.Basic2TestMessage defaultValue);
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 7;</code>
   */

  crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 8;</code>
   */
  java.util.List<crenjoy.protobuf.Basic2TestMessage> 
      getTestBasicListList();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 8;</code>
   */
  crenjoy.protobuf.Basic2TestMessage getTestBasicList(int index);
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 8;</code>
   */
  int getTestBasicListCount();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 8;</code>
   */
  java.util.List<? extends crenjoy.protobuf.Basic2TestMessageOrBuilder> 
      getTestBasicListOrBuilderList();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 8;</code>
   */
  crenjoy.protobuf.Basic2TestMessageOrBuilder getTestBasicListOrBuilder(
      int index);
}
