// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface TestMessageMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.TestMessageMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  int getTestBasicMapCount();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  boolean containsTestBasicMap(
      java.lang.String key);
  /**
   * Use {@link #getTestBasicMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
  getTestBasicMap();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
  getTestBasicMapMap();
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */

  /* nullable */
crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrDefault(
      java.lang.String key,
      /* nullable */
crenjoy.protobuf.Basic2TestMessage defaultValue);
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */

  crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrThrow(
      java.lang.String key);
}
