// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

public interface TestMessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crenjoy.protobuf.TestMessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  java.util.List<crenjoy.protobuf.Basic2TestMessage> 
      getTestBasicListList();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  crenjoy.protobuf.Basic2TestMessage getTestBasicList(int index);
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  int getTestBasicListCount();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  java.util.List<? extends crenjoy.protobuf.Basic2TestMessageOrBuilder> 
      getTestBasicListOrBuilderList();
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  crenjoy.protobuf.Basic2TestMessageOrBuilder getTestBasicListOrBuilder(
      int index);
}
