// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

/**
 * Protobuf type {@code crenjoy.protobuf.TestMessageMap}
 */
public final class TestMessageMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.TestMessageMap)
    TestMessageMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestMessageMap.newBuilder() to construct.
  private TestMessageMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestMessageMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestMessageMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetTestBasicMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            crenjoy.protobuf.TestMessageMap.class, crenjoy.protobuf.TestMessageMap.Builder.class);
  }

  public static final int TEST_BASIC_MAP_FIELD_NUMBER = 1;
  private static final class TestBasicMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, crenjoy.protobuf.Basic2TestMessage> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, crenjoy.protobuf.Basic2TestMessage>newDefaultInstance(
                crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_TestBasicMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                crenjoy.protobuf.Basic2TestMessage.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, crenjoy.protobuf.Basic2TestMessage> testBasicMap_;
  private com.google.protobuf.MapField<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
  internalGetTestBasicMap() {
    if (testBasicMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TestBasicMapDefaultEntryHolder.defaultEntry);
    }
    return testBasicMap_;
  }

  public int getTestBasicMapCount() {
    return internalGetTestBasicMap().getMap().size();
  }
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */

  @java.lang.Override
  public boolean containsTestBasicMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTestBasicMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTestBasicMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> getTestBasicMap() {
    return getTestBasicMapMap();
  }
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> getTestBasicMapMap() {
    return internalGetTestBasicMap().getMap();
  }
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  @java.lang.Override

  public crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrDefault(
      java.lang.String key,
      crenjoy.protobuf.Basic2TestMessage defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> map =
        internalGetTestBasicMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
   */
  @java.lang.Override

  public crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> map =
        internalGetTestBasicMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTestBasicMap(),
        TestBasicMapDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, crenjoy.protobuf.Basic2TestMessage> entry
         : internalGetTestBasicMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
      testBasicMap__ = TestBasicMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, testBasicMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof crenjoy.protobuf.TestMessageMap)) {
      return super.equals(obj);
    }
    crenjoy.protobuf.TestMessageMap other = (crenjoy.protobuf.TestMessageMap) obj;

    if (!internalGetTestBasicMap().equals(
        other.internalGetTestBasicMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetTestBasicMap().getMap().isEmpty()) {
      hash = (37 * hash) + TEST_BASIC_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTestBasicMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static crenjoy.protobuf.TestMessageMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(crenjoy.protobuf.TestMessageMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crenjoy.protobuf.TestMessageMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.TestMessageMap)
      crenjoy.protobuf.TestMessageMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTestBasicMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableTestBasicMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crenjoy.protobuf.TestMessageMap.class, crenjoy.protobuf.TestMessageMap.Builder.class);
    }

    // Construct using crenjoy.protobuf.TestMessageMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableTestBasicMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageMap_descriptor;
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageMap getDefaultInstanceForType() {
      return crenjoy.protobuf.TestMessageMap.getDefaultInstance();
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageMap build() {
      crenjoy.protobuf.TestMessageMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageMap buildPartial() {
      crenjoy.protobuf.TestMessageMap result = new crenjoy.protobuf.TestMessageMap(this);
      int from_bitField0_ = bitField0_;
      result.testBasicMap_ = internalGetTestBasicMap();
      result.testBasicMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof crenjoy.protobuf.TestMessageMap) {
        return mergeFrom((crenjoy.protobuf.TestMessageMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(crenjoy.protobuf.TestMessageMap other) {
      if (other == crenjoy.protobuf.TestMessageMap.getDefaultInstance()) return this;
      internalGetMutableTestBasicMap().mergeFrom(
          other.internalGetTestBasicMap());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
              testBasicMap__ = input.readMessage(
                  TestBasicMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTestBasicMap().getMutableMap().put(
                  testBasicMap__.getKey(), testBasicMap__.getValue());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, crenjoy.protobuf.Basic2TestMessage> testBasicMap_;
    private com.google.protobuf.MapField<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
    internalGetTestBasicMap() {
      if (testBasicMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TestBasicMapDefaultEntryHolder.defaultEntry);
      }
      return testBasicMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
    internalGetMutableTestBasicMap() {
      onChanged();;
      if (testBasicMap_ == null) {
        testBasicMap_ = com.google.protobuf.MapField.newMapField(
            TestBasicMapDefaultEntryHolder.defaultEntry);
      }
      if (!testBasicMap_.isMutable()) {
        testBasicMap_ = testBasicMap_.copy();
      }
      return testBasicMap_;
    }

    public int getTestBasicMapCount() {
      return internalGetTestBasicMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */

    @java.lang.Override
    public boolean containsTestBasicMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTestBasicMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTestBasicMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> getTestBasicMap() {
      return getTestBasicMapMap();
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> getTestBasicMapMap() {
      return internalGetTestBasicMap().getMap();
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */
    @java.lang.Override

    public crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrDefault(
        java.lang.String key,
        crenjoy.protobuf.Basic2TestMessage defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> map =
          internalGetTestBasicMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */
    @java.lang.Override

    public crenjoy.protobuf.Basic2TestMessage getTestBasicMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> map =
          internalGetTestBasicMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTestBasicMap() {
      internalGetMutableTestBasicMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */

    public Builder removeTestBasicMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTestBasicMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage>
    getMutableTestBasicMap() {
      return internalGetMutableTestBasicMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */
    public Builder putTestBasicMap(
        java.lang.String key,
        crenjoy.protobuf.Basic2TestMessage value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableTestBasicMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .crenjoy.protobuf.Basic2TestMessage&gt; test_basic_map = 1;</code>
     */

    public Builder putAllTestBasicMap(
        java.util.Map<java.lang.String, crenjoy.protobuf.Basic2TestMessage> values) {
      internalGetMutableTestBasicMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.TestMessageMap)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.TestMessageMap)
  private static final crenjoy.protobuf.TestMessageMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new crenjoy.protobuf.TestMessageMap();
  }

  public static crenjoy.protobuf.TestMessageMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestMessageMap>
      PARSER = new com.google.protobuf.AbstractParser<TestMessageMap>() {
    @java.lang.Override
    public TestMessageMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TestMessageMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestMessageMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public crenjoy.protobuf.TestMessageMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

