// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crenjoy/protobuf/basic_test.proto

package crenjoy.protobuf;

/**
 * Protobuf type {@code crenjoy.protobuf.TestMessageList}
 */
public final class TestMessageList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crenjoy.protobuf.TestMessageList)
    TestMessageListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestMessageList.newBuilder() to construct.
  private TestMessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestMessageList() {
    testBasicList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestMessageList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            crenjoy.protobuf.TestMessageList.class, crenjoy.protobuf.TestMessageList.Builder.class);
  }

  public static final int TEST_BASIC_LIST_FIELD_NUMBER = 1;
  private java.util.List<crenjoy.protobuf.Basic2TestMessage> testBasicList_;
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<crenjoy.protobuf.Basic2TestMessage> getTestBasicListList() {
    return testBasicList_;
  }
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends crenjoy.protobuf.Basic2TestMessageOrBuilder> 
      getTestBasicListOrBuilderList() {
    return testBasicList_;
  }
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  @java.lang.Override
  public int getTestBasicListCount() {
    return testBasicList_.size();
  }
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  @java.lang.Override
  public crenjoy.protobuf.Basic2TestMessage getTestBasicList(int index) {
    return testBasicList_.get(index);
  }
  /**
   * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
   */
  @java.lang.Override
  public crenjoy.protobuf.Basic2TestMessageOrBuilder getTestBasicListOrBuilder(
      int index) {
    return testBasicList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < testBasicList_.size(); i++) {
      output.writeMessage(1, testBasicList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < testBasicList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, testBasicList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof crenjoy.protobuf.TestMessageList)) {
      return super.equals(obj);
    }
    crenjoy.protobuf.TestMessageList other = (crenjoy.protobuf.TestMessageList) obj;

    if (!getTestBasicListList()
        .equals(other.getTestBasicListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTestBasicListCount() > 0) {
      hash = (37 * hash) + TEST_BASIC_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getTestBasicListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static crenjoy.protobuf.TestMessageList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static crenjoy.protobuf.TestMessageList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(crenjoy.protobuf.TestMessageList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crenjoy.protobuf.TestMessageList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crenjoy.protobuf.TestMessageList)
      crenjoy.protobuf.TestMessageListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crenjoy.protobuf.TestMessageList.class, crenjoy.protobuf.TestMessageList.Builder.class);
    }

    // Construct using crenjoy.protobuf.TestMessageList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (testBasicListBuilder_ == null) {
        testBasicList_ = java.util.Collections.emptyList();
      } else {
        testBasicList_ = null;
        testBasicListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return crenjoy.protobuf.BasicTestMessageProto.internal_static_crenjoy_protobuf_TestMessageList_descriptor;
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageList getDefaultInstanceForType() {
      return crenjoy.protobuf.TestMessageList.getDefaultInstance();
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageList build() {
      crenjoy.protobuf.TestMessageList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public crenjoy.protobuf.TestMessageList buildPartial() {
      crenjoy.protobuf.TestMessageList result = new crenjoy.protobuf.TestMessageList(this);
      int from_bitField0_ = bitField0_;
      if (testBasicListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          testBasicList_ = java.util.Collections.unmodifiableList(testBasicList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.testBasicList_ = testBasicList_;
      } else {
        result.testBasicList_ = testBasicListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof crenjoy.protobuf.TestMessageList) {
        return mergeFrom((crenjoy.protobuf.TestMessageList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(crenjoy.protobuf.TestMessageList other) {
      if (other == crenjoy.protobuf.TestMessageList.getDefaultInstance()) return this;
      if (testBasicListBuilder_ == null) {
        if (!other.testBasicList_.isEmpty()) {
          if (testBasicList_.isEmpty()) {
            testBasicList_ = other.testBasicList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTestBasicListIsMutable();
            testBasicList_.addAll(other.testBasicList_);
          }
          onChanged();
        }
      } else {
        if (!other.testBasicList_.isEmpty()) {
          if (testBasicListBuilder_.isEmpty()) {
            testBasicListBuilder_.dispose();
            testBasicListBuilder_ = null;
            testBasicList_ = other.testBasicList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            testBasicListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTestBasicListFieldBuilder() : null;
          } else {
            testBasicListBuilder_.addAllMessages(other.testBasicList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              crenjoy.protobuf.Basic2TestMessage m =
                  input.readMessage(
                      crenjoy.protobuf.Basic2TestMessage.parser(),
                      extensionRegistry);
              if (testBasicListBuilder_ == null) {
                ensureTestBasicListIsMutable();
                testBasicList_.add(m);
              } else {
                testBasicListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<crenjoy.protobuf.Basic2TestMessage> testBasicList_ =
      java.util.Collections.emptyList();
    private void ensureTestBasicListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        testBasicList_ = new java.util.ArrayList<crenjoy.protobuf.Basic2TestMessage>(testBasicList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        crenjoy.protobuf.Basic2TestMessage, crenjoy.protobuf.Basic2TestMessage.Builder, crenjoy.protobuf.Basic2TestMessageOrBuilder> testBasicListBuilder_;

    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public java.util.List<crenjoy.protobuf.Basic2TestMessage> getTestBasicListList() {
      if (testBasicListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(testBasicList_);
      } else {
        return testBasicListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public int getTestBasicListCount() {
      if (testBasicListBuilder_ == null) {
        return testBasicList_.size();
      } else {
        return testBasicListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public crenjoy.protobuf.Basic2TestMessage getTestBasicList(int index) {
      if (testBasicListBuilder_ == null) {
        return testBasicList_.get(index);
      } else {
        return testBasicListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder setTestBasicList(
        int index, crenjoy.protobuf.Basic2TestMessage value) {
      if (testBasicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestBasicListIsMutable();
        testBasicList_.set(index, value);
        onChanged();
      } else {
        testBasicListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder setTestBasicList(
        int index, crenjoy.protobuf.Basic2TestMessage.Builder builderForValue) {
      if (testBasicListBuilder_ == null) {
        ensureTestBasicListIsMutable();
        testBasicList_.set(index, builderForValue.build());
        onChanged();
      } else {
        testBasicListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder addTestBasicList(crenjoy.protobuf.Basic2TestMessage value) {
      if (testBasicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestBasicListIsMutable();
        testBasicList_.add(value);
        onChanged();
      } else {
        testBasicListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder addTestBasicList(
        int index, crenjoy.protobuf.Basic2TestMessage value) {
      if (testBasicListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTestBasicListIsMutable();
        testBasicList_.add(index, value);
        onChanged();
      } else {
        testBasicListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder addTestBasicList(
        crenjoy.protobuf.Basic2TestMessage.Builder builderForValue) {
      if (testBasicListBuilder_ == null) {
        ensureTestBasicListIsMutable();
        testBasicList_.add(builderForValue.build());
        onChanged();
      } else {
        testBasicListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder addTestBasicList(
        int index, crenjoy.protobuf.Basic2TestMessage.Builder builderForValue) {
      if (testBasicListBuilder_ == null) {
        ensureTestBasicListIsMutable();
        testBasicList_.add(index, builderForValue.build());
        onChanged();
      } else {
        testBasicListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder addAllTestBasicList(
        java.lang.Iterable<? extends crenjoy.protobuf.Basic2TestMessage> values) {
      if (testBasicListBuilder_ == null) {
        ensureTestBasicListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, testBasicList_);
        onChanged();
      } else {
        testBasicListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder clearTestBasicList() {
      if (testBasicListBuilder_ == null) {
        testBasicList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        testBasicListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public Builder removeTestBasicList(int index) {
      if (testBasicListBuilder_ == null) {
        ensureTestBasicListIsMutable();
        testBasicList_.remove(index);
        onChanged();
      } else {
        testBasicListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public crenjoy.protobuf.Basic2TestMessage.Builder getTestBasicListBuilder(
        int index) {
      return getTestBasicListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public crenjoy.protobuf.Basic2TestMessageOrBuilder getTestBasicListOrBuilder(
        int index) {
      if (testBasicListBuilder_ == null) {
        return testBasicList_.get(index);  } else {
        return testBasicListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public java.util.List<? extends crenjoy.protobuf.Basic2TestMessageOrBuilder> 
         getTestBasicListOrBuilderList() {
      if (testBasicListBuilder_ != null) {
        return testBasicListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(testBasicList_);
      }
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public crenjoy.protobuf.Basic2TestMessage.Builder addTestBasicListBuilder() {
      return getTestBasicListFieldBuilder().addBuilder(
          crenjoy.protobuf.Basic2TestMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public crenjoy.protobuf.Basic2TestMessage.Builder addTestBasicListBuilder(
        int index) {
      return getTestBasicListFieldBuilder().addBuilder(
          index, crenjoy.protobuf.Basic2TestMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .crenjoy.protobuf.Basic2TestMessage test_basic_list = 1;</code>
     */
    public java.util.List<crenjoy.protobuf.Basic2TestMessage.Builder> 
         getTestBasicListBuilderList() {
      return getTestBasicListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        crenjoy.protobuf.Basic2TestMessage, crenjoy.protobuf.Basic2TestMessage.Builder, crenjoy.protobuf.Basic2TestMessageOrBuilder> 
        getTestBasicListFieldBuilder() {
      if (testBasicListBuilder_ == null) {
        testBasicListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            crenjoy.protobuf.Basic2TestMessage, crenjoy.protobuf.Basic2TestMessage.Builder, crenjoy.protobuf.Basic2TestMessageOrBuilder>(
                testBasicList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        testBasicList_ = null;
      }
      return testBasicListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crenjoy.protobuf.TestMessageList)
  }

  // @@protoc_insertion_point(class_scope:crenjoy.protobuf.TestMessageList)
  private static final crenjoy.protobuf.TestMessageList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new crenjoy.protobuf.TestMessageList();
  }

  public static crenjoy.protobuf.TestMessageList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestMessageList>
      PARSER = new com.google.protobuf.AbstractParser<TestMessageList>() {
    @java.lang.Override
    public TestMessageList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TestMessageList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestMessageList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public crenjoy.protobuf.TestMessageList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

